DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

LearningOnline/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.static import serve

import xadmin
from LearningOnline.settings import MEDIA_ROOT
from apps.operations.views import IndexView
from apps.users.views import LoginView, LogoutView, RegisterView, BehaviorView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(), name="index"),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # configure access url for uploading images
    url('media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # url('static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    url('org/', include(('apps.organizations.urls', "organizations"), namespace="org")),
    url('course/', include(('apps.courses.urls', "courses"), namespace="course")),
    url('op/', include(('apps.operations.urls', "operations"), namespace="op")),
    url('users/', include(('apps.users.urls', "users"), namespace="users")),
    path('behavior-questions/', BehaviorView.as_view(), name="behavior-questions"),

]

apps/courses/urls.py
from django.conf.urls import url
from django.urls import path

from apps.courses.views import CourseListView, CourseDetailView, CourseLessonView, CourseCommentView, CourseVideoView

urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name="list"),
    path('<int:course_id>/', CourseDetailView.as_view(), name="detail"),
    path('<int:course_id>/lesson/', CourseLessonView.as_view(), name="lesson"),
    path('<int:course_id>/comment/$', CourseCommentView.as_view(), name="comment"),
    path('<int:course_id>/video/<int:video_id>', CourseVideoView.as_view(), name="video"),

]

apps/operations/urls.py
from django.conf.urls import url

from apps.operations.views import AddFavView, AddCommentView

urlpatterns = [
    url(r'fav/$', AddFavView.as_view(), name="fav"),
    url(r'comment/$', AddCommentView.as_view(), name="comment"),

]

apps/organizations/urls.py
from django.conf.urls import url
from django.urls import path

from apps.organizations.views import OrgView, AddConsultView, OrgHomeView, OrgTeacherView, OrgCourseView, OrgDescView, \
    TeacherView, TeacherDetailView

urlpatterns = [
    url(r'^list/$', OrgView.as_view(), name="list"),
    url(r'^add_consult/', AddConsultView.as_view(), name="add_consult"),
    path('<int:org_id>/', OrgHomeView.as_view(), name="home"),
    path('<int:org_id>/teacher/', OrgTeacherView.as_view(), name="teacher"),
    path('<int:org_id>/course/', OrgCourseView.as_view(), name="course"),
    path('<int:org_id>/desc/', OrgDescView.as_view(), name="desc"),
    path('teachers/', TeacherView.as_view(), name="teacher-list"),
    path('teacher_list/<int:teacher_id>/', TeacherDetailView.as_view(), name="teacher-detail"),

]

apps/users/urls.py
from django.conf.urls import url

from apps.users.views import UserInfoView, UploadImageView, ChangePwdView, MyCourseView, MyFavOrgView, MyFavTeacherView, \
    MyFavCourseView, MyMessageView

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name="info"),
    url(r'^image/upload/$', UploadImageView.as_view(), name="image-upload"),
    url(r'^update/pwd/$', ChangePwdView.as_view(), name="update-pwd"),
    url(r'^mycourse/$', MyCourseView.as_view(), name="mycourse"),
    url(r'^myfavorg/$', MyFavOrgView.as_view(), name="myfav_org"),
    url(r'^myfav_teacher/$', MyFavTeacherView.as_view(), name="myfav_teachers"),
    url(r'^myfav_course/$', MyFavCourseView.as_view(), name="myfav_course"),
    url(r'^messages/$', MyMessageView.as_view(), name="messages"),
]

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/course-lesson.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}lesson-welearning{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp" style="margin-top:60px">
            <ul class="crumbs">
                <li><a href="{% url "index" %}">Home</a>></li>
                <li><a href="{% url "course:list" %}">Courses</a>></li>
                <li><a href="">{{ course.name }}</a>></li>
                <li>Lesson Info</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                        <span class="meta">difficulty</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.time_duration }} minutes</span>
                        <span class="meta">time duration</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">student number</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">
            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active active" id="learnOn"
                                       href="{% url "course:lesson" course.id %}"><span>Lessons</span></a></li>
                                <li><a id="commentOn" class="" href="{% url "course:comment" course.id %}"><span>Comments</span></a></li>
                            </ul>
                        </div>
                        {% if course.notice %}
                            <div id="notice" class="clearfix">
                                <div class="l"><strong>Notice: </strong> <a
                                        href="javascript:void(0)">{{ course.notice }}</a></div>
                            </div>
                        {% endif %}
                        <div class="mod-chapters">
                            {% for lesson in course.lesson_set.all %}
                                <div class="chapter chapter-active">
                                    <h3>
                                        <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                    </h3>
                                    <ul class="video">
                                        {% for video in lesson.video_set.all %}
                                            <li>
                                   <a target="_blank" href='{% url "course:video" course.id video.id %}' class="J-media-item studyvideo">
                                                    {{ video.name }}({{ video.time_duration }}min)<i
                                                        class="study-state"></i>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="aside r">
                        <div class="bd">
                            <div class="box mb40">
                                <h4>Resources</h4>
                                <ul class="downlist">
                                    {% for resource in course_resource %}
                                    <li>
                                        <span><i class="aui-iconfont aui-icon-file"></i>{{ resource.name }}</span>
                                        <a href="{{resource.file.url}}" class="downcode"
                                           target="_blank" download="" data-id="274" title="">download</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="{% url "org:teacher-detail" course.teacher.id %}" target="_blank">
                                        <img src='{{ course.teacher.image.url }}' width='80' height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="{% url "org:teacher-detail" course.teacher.id %}" target="_blank">{{ course.teacher.name }}</a>
        </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>Requirements</dt>
                                        <dd class="autowrap">{{ course.youneed_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>What you will learn?</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for course in recommended_courses %}
                                            <li class="curr">
                                                <a href="{% url "course:detail" course.id %}" target="_blank">
                                                    <img src="{{ course.image.url }}"
                                                         alt="{{ course.name }}">
                                                    <span class="name autowrap">{{ course.name }}</span>
                                                </a>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-fav-course.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}personalcenter - welearning{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs" style="margin-top:60px" >
                <li><a href="{% url "index" %}">Home</a>></li>
                <li><a href="{% url "users:info" %}">Personal Center</a>></li>
                <li>Personal Info</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
    <div class="wp list personal_list">
        <div class="left">
            <ul>
                <li class="{% if current_page == "info" %}active2{% endif %}"><a href="{% url "users:info" %}">Personal Info</a></li>
                <li class="{% if current_page == "mycourse" %}active2{% endif %}"><a href="{% url "users:mycourse" %}">My Courses</a></li>
                <li class="{% if current_page == 'myfav_org' or current_page == 'myfav_teacher' or current_page == 'myfav_course' %}active2{% endif %}"><a href="{% url "users:myfav_org" %}">My Favorites</a></li>
                <li class="{% if current_page == "message" %}active2{% endif %}">
                    <a href="{% url "users:messages" %}" style="position: relative;">
                        My Messages
                    </a>
                </li>
            </ul>
        </div>
      <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1 style="font-size: 20px">My Favorites</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_org' %}">Organizations</a> </li>
                        <li><a href="{% url 'users:myfav_teachers' %}">Teachers </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">Courses</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box" style="border: 1px solid #eaeaea;">
                            <a href="{% url 'course:detail' course.id %}">
                                <img width="214" height="190" src="{{ course.image.url }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl"><i class="key">{{ course.learn_times }}</i>minutes</span>
                                <span class="fr">{{ course.students }} enrolled</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    $('.jsDeleteFav_course').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav' %}",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
</script>
{% endblock %}

templates/usercenter-fav-org.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}personalcenter - welearning{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs" style="margin-top:60px" >
                <li><a href="{% url "index" %}">Home</a>></li>
                <li><a href="{% url "users:info" %}">Personal Center</a>></li>
                <li>Personal Info</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
    <div class="wp list personal_list">
        <div class="left">
            <ul>
                <li class="{% if current_page == "info" %}active2{% endif %}"><a href="{% url "users:info" %}">Personal Info</a></li>
                <li class="{% if current_page == "mycourse" %}active2{% endif %}"><a href="{% url "users:mycourse" %}">My Courses</a></li>
                <li class="{% if current_page == 'myfav_org' or current_page == 'myfav_teacher' or current_page == 'myfav_course' %}active2{% endif %}"><a href="{% url "users:myfav_org" %}">My Favorites</a></li>
                <li class="{% if current_page == "message" %}active2{% endif %}">
                    <a href="{% url "users:messages" %}" style="position: relative;">
                        My Messages
                    </a>
                </li>
            </ul>
        </div>
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1 style="font-size: 20px">My Favorites</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:myfav_org' %}">Organizations</a> </li>
                        <li><a href="{% url 'users:myfav_teachers' %}">Teachers</a></li>
                        <li><a href="{% url 'users:myfav_course' %}">Courses</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:home' org.id %}">
                                    <img width="160" height="90" src="{{ org.image.url }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                {% if org.is_auth %}
                                    <img src="{% static 'images/authentication.svg' %}"/>
                                {% endif %}
                                {% if org.is_gold %}
                                    <img src="{% static 'images/gold.svg' %}"/>
                                {% endif %}
                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    $('.jsDeleteFav_org').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav' %}",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
</script>
{% endblock %}